const shopActionTypes = {
  FETCH_APICALL_START: "FETCH_APICALL_START",
  FETCH_APICALL_SUCCESS: "FETCH_APICALL_SUCCESS",
  FETCH_APICALL_FAILED: "FETCH_APICALL_FAILED",
};

export default shopActionTypes;
